import { Helmet } from "react-helmet";

let generalStyle = {
    color: "black",
    padding: 20,
    fontFamily: "Sans-Serif",
    textAlign: "center"
  }

  let x = window.innerWidth
  let widthx = x*(10/100)

export default function markManson () {

    return (
<>

<Helmet>  
  <title>The Subtle Art of Not Giving a F*ck - Mark Manson</title>
  </Helmet>   


<h1 style= {generalStyle}> <b> The Subtle Art of Not Giving a F*ck - Mark Manson </b> </h1>

<div style={{textAlign: "justify", paddingRight:widthx, paddingLeft: widthx}}>

<p> 1. Playboy-style passage about how the program could help in romancing “a Chinese girl”; and also some boasting about Zuckerberg’s own computer prowess (“Mark’s mouse, alone, has moved enough to go around the world . . . twice.”)
</p><p> 2. There’s a saying in Texas: “The smallest dog barks the loudest.” A confident man doesn’t feel a need to prove that he’s confident. A rich woman doesn’t feel a need to convince anybody that she’s rich.
</p><p> 3. There’s a saying in Texas: “The smallest dog barks the loudest.” A confident man doesn’t feel a need to prove that he’s confident. A rich woman doesn’t feel a need to convince anybody that she’s rich. Either you are or you are not. And if you’re dreaming of something all the time, then you’re reinforcing the same unconscious reality over and over: that you are not that.
</p><p> 4. And while there’s nothing wrong with good business, the problem is that giving too many fucks is bad for your mental health. It causes you to become overly attached to the superficial and fake, to dedicate your life to chasing a mirage of happiness and satisfaction. The key to a good life is not giving a fuck about more; it’s giving a fuck about less, giving a fuck about only what is true and immediate and important. The
</p><p> 5. This is a total mind-fuck. So I’ll give you a minute to unpretzel your brain and maybe read that again: Wanting positive experience is a negative experience; accepting negative experience is a positive experience. It’s what the philosopher Alan Watts used to refer to as “the backwards law”— the idea that the more you pursue feeling better all the time, the less satisfied you become, as pursuing something only reinforces the fact that  you lack it in the first place. The more you desperately want to be rich, the more poor and unworthy you feel, regardless of how much money you actually make. The more you desperately want to be sexy and desired, the uglier you come to see yourself, regardless of your actual physical appearance. The more you desperately want to be happy and loved, the lonelier and more afraid you become, regardless of those who surround you.
</p><p> 6. This is a total mind-fuck. So I’ll give you a minute to unpretzel your brain and maybe read that again: Wanting positive experience is a negative experience; accepting negative experience is a positive experience. It’s what the philosopher Alan Watts used to refer to as “the backwards law”— the idea that the more you pursue feeling better all the time, the less satisfied you become, as pursuing something only reinforces the fact that  you lack it in the first place. The more you desperately want to be rich, the more poor and unworthy you feel, regardless of how much money you actually make. The more you desperately want to be sexy and desired, the uglier you come to see yourself, regardless of your actual physical appearance. The more you desperately want to be happy and loved, the lonelier and more afraid you become, regardless of those who surround you. The more you want to be spiritually enlightened, the more self-centered and shallow you become in trying to get there.
</p><p> 7. As the existential philosopher Albert Camus said (and I’m pretty sure he wasn’t on LSD at the time): “You will never be happy if you continue to search for what happiness consists of. You will never live if you are looking for the meaning of life.”
</p><p> 8. Ever notice that sometimes when you care less about something, you do better at it? Notice how it’s often the person who is the least invested in the success of something that actually ends up achieving it? Notice how sometimes when you stop giving a fuck, everything seems to fall into place?
</p><p> 9. What’s interesting about the backwards law is that it’s called “backwards” for a reason: not giving a fuck works in reverse. If pursuing the positive is a negative, then pursuing the negative generates the positive. The pain you pursue in the gym results in better all-around health and energy. The failures in business are what lead to a better understanding of  what’s necessary to be successful. Being open with your insecurities paradoxically makes you more confident and charismatic around others. The
</p><p> 10. Seriously, I could keep going, but you get the point. Everything worthwhile in life is won through surmounting the associated negative experience.
</p><p> 11. Seriously, I could keep going, but you get the point. Everything worthwhile in life is won through surmounting the associated negative experience. Any attempt to escape the negative, to avoid it or quash it or silence it, only backfires. The avoidance of suffering is a form of suffering.
</p><p> 12. Seriously, I could keep going, but you get the point. Everything worthwhile in life is won through surmounting the associated negative experience. Any attempt to escape the negative, to avoid it or quash it or silence it, only backfires. The avoidance of suffering is a form of suffering. The avoidance of struggle is a struggle. The denial of failure is a failure.
</p><p> 13. Seriously, I could keep going, but you get the point. Everything worthwhile in life is won through surmounting the associated negative experience. Any attempt to escape the negative, to avoid it or quash it or silence it, only backfires. The avoidance of suffering is a form of suffering. The avoidance of struggle is a struggle. The denial of failure is a failure. Hiding what is shameful is itself a form of shame.
</p><p> 14. To try to avoid pain is to give too many fucks about pain.
</p><p> 15. To try to avoid pain is to give too many fucks about pain. In contrast, if you’re able to not give a fuck about the pain, you become unstoppable.
</p><p> 16. To not give a fuck is to stare down life’s most terrifying and difficult challenges and still take action.
</p><p> 17. There is a subtle art to not giving a fuck. And though the concept may sound ridiculous and I may sound like an asshole, what I’m talking about here is essentially learning how to focus and prioritize your thoughts effectively—how to pick and choose what matters to you and what does not matter to you based on finely honed personal values. This is incredibly difficult. It takes a lifetime of practice and discipline to achieve. And you will regularly fail. But it is perhaps the most worthy struggle one can undertake in one’s life. It is perhaps the only struggle in one’s life. Because when you give too many fucks—when you give a fuck about everyone and everything—you will feel that you’re perpetually entitled to be comfortable and happy at all times, that everything is supposed to be just exactly the fucking way you want it to be. This is a sickness. And it will eat you alive. You will see every adversity as an injustice, every challenge as a failure, every inconvenience as a personal slight, every disagreement as a betrayal. You will be confined to your own petty, skull-sized hell, burning with entitlement and bluster, running circles around your very own personal Feedback Loop from Hell, in constant motion yet arriving nowhere.
</p><p> 18. Let’s be clear. There’s absolutely nothing admirable or confident about indifference. People who are indifferent are lame and scared. They’re couch potatoes and Internet trolls. In fact, indifferent people often attempt to be indifferent because in reality they give way too many fucks. They give a fuck about what everyone thinks of their hair, so they never bother washing or combing it. They give a fuck about what everyone thinks of their ideas, so they hide behind sarcasm and self-righteous snark. They’re afraid to let anyone get close to them, so they imagine themselves as some special, unique snowflake who has problems that nobody else would ever understand. Indifferent
</p><p> 19. Let’s be clear. There’s absolutely nothing admirable or confident about indifference. People who are indifferent are lame and scared. They’re couch potatoes and Internet trolls. In fact, indifferent people often attempt to be indifferent because in reality they give way too many fucks. They give a fuck about what everyone thinks of their hair, so they never bother washing or combing it. They give a fuck about what everyone thinks of their ideas, so they hide behind sarcasm and self-righteous snark. They’re afraid to let anyone get close to them, so they imagine themselves as some special, unique snowflake who has problems that nobody else would ever understand. Indifferent people are afraid of the world and the repercussions of their own choices. That’s why they don’t make any meaningful choices. They hide in a gray, emotionless pit of their own making, self-absorbed and self-pitying, perpetually distracting themselves from this unfortunate thing demanding their time and energy called life.
</p><p> 20. This is what is so admirable. No, not me, dumbass—the overcoming adversity stuff, the willingness to be different, an outcast, a pariah, all for the sake of one’s own values.
</p><p> 21. Because here’s another sneaky little truth about life. You can’t be an important and life-changing presence for some people without also being a joke and an embarrassment to others.
</p><p> 22. If you find yourself consistently giving too many fucks about trivial shit that bothers you—your ex-boyfriend’s new Facebook picture, how quickly the batteries die in the TV remote, missing out on yet another two-for-one sale on hand sanitizer—chances are you don’t have much going on in your life to give a legitimate fuck about.
</p><p> 23. On the contrary, I see practical enlightenment as becoming comfortable with the idea that some suffering is always inevitable —that no matter what you do, life is comprised of failures, loss, regrets, and even death.
</p><p> 24. On the contrary, I see practical enlightenment as becoming comfortable with the idea that some suffering is always inevitable —that no matter what you do, life is comprised of failures, loss, regrets, and even death. Because once you become comfortable with all the shit that life throws at you (and it will throw a lot of shit, trust me), you become invincible in a sort of low-level spiritual way. After all, the only way to overcome pain is to first learn how to bear it.
</p><p> 25. In fact, the prince came to know what the rest of us have always kind of known: that suffering totally sucks. And it’s not necessarily that meaningful either.
</p><p> 26. In fact, the prince came to know what the rest of us have always kind of known: that suffering totally sucks. And it’s not necessarily that meaningful either. As with being rich, there is no value in suffering when it’s done without purpose.
</p><p> 27. One of those realizations was this: that life itself is a form of suffering.
</p><p> 28. Years later, the prince would build his own philosophy and share it with the world, and this would be its first and central tenet: that pain and loss are inevitable and we should let go of trying to resist them.
</p><p> 29. The premise is that happiness is algorithmic, that it can be worked for and earned and achieved as if it were getting accepted to law school or building a really complicated Lego set. If I achieve X, then I can be happy. If I look like Y, then I can be happy. If I can be with a person like Z, then I can be happy.
</p><p> 30. This premise, though, is the problem. Happiness is not a solvable equation.
</p><p> 31. When you solve your problem of not spending enough time with your partner by designating Wednesday night “date night,” you generate new problems, such as figuring out what to do every Wednesday that you both won’t hate, making sure you have enough money for nice dinners, rediscovering the chemistry and spark you two feel you’ve lost, and unraveling the logistics of fucking in a small bathtub filled with too many bubbles.
</p><p> 32. Problems never stop; they merely get exchanged and/or upgraded.
</p><p> 33. True happiness occurs only when you find the problems you enjoy having and enjoy solving.
</p><p> 34. Whatever your problems are, the concept is the same: solve problems; be happy. Unfortunately, for many people, life doesn’t feel that simple.
</p><p> 35. Whatever your problems are, the concept is the same: solve problems; be happy. Unfortunately, for many people, life doesn’t feel that simple. That’s because they fuck things up in at least one of two ways: 1. Denial. Some people deny that their problems exist in the first place.
</p><p> 36. Whatever your problems are, the concept is the same: solve problems; be happy. Unfortunately, for many people, life doesn’t feel that simple. That’s because they fuck things up in at least one of two ways: 1. Denial. Some people deny that their problems exist in the first place. And because they deny reality, they must constantly delude or distract themselves
</p><p> 37. Much as the pain of touching a hot stove teaches you not to touch it again, the sadness of being alone teaches you not to do the things that made you feel so alone again.
</p><p> 38. An obsession and overinvestment in emotion fails us for the simple reason that emotions never last.
</p><p> 39. Everything comes with an inherent sacrifice—whatever makes us feel good will also inevitably make us feel bad.
</p><p> 40. You can’t win if you don’t play.
</p><p> 41. What determines your success isn’t, “What do you want to enjoy?” The relevant question is, “What pain do you want to sustain?”
</p><p> 42. The path to happiness is a path full of shitheaps and shame. You have to choose something. You can’t have a pain-free life. It can’t all be roses and unicorns all the time. Pleasure is the easy question. And pretty much all of us have a similar answer.
</p><p> 43. was in love with the result—the image of me on stage, people cheering, me rocking out, pouring my heart into what I was playing—but I wasn’t in love with the process. And because of that, I failed at it.
</p><p> 44. I wanted the reward and not the struggle. I wanted the result and not the process. I was in love with not the fight but only the victory.
</p><p> 45. The common cultural narratives would tell me that I somehow failed myself, that I’m a quitter or a loser, that I just didn’t “have it,” that I gave up on my dream and that maybe I let myself succumb to the pressures of society. But the truth is far less interesting than any of these explanations. The truth is, I thought I wanted something, but it turns out I didn’t. End of story. I wanted the reward and not the struggle. I wanted the result and not the process. I was in love with not the fight but only the victory.
</p><p> 46. The common cultural narratives would tell me that I somehow failed myself, that I’m a quitter or a loser, that I just didn’t “have it,” that I gave up on my dream and that maybe I let myself succumb to the pressures of society. But the truth is far less interesting than any of these explanations. The truth is, I thought I wanted something, but it turns out I didn’t. End of story. I wanted the reward and not the struggle. I wanted the result and not the process. I was in love with not the fight but only the victory. And life doesn’t work that way.
</p><p> 47. Who you are is defined by what you’re willing to struggle for.
</p><p> 48. This is not about willpower or grit. This is not another admonishment of “no pain, no gain.” This is the most simple and basic component of life: our struggles determine our successes. Our problems birth our happiness, along with slightly better, slightly upgraded problems.
</p><p> 49. This is not about willpower or grit. This is not another admonishment of “no pain, no gain.” This is the most simple and basic component of life: our struggles determine our successes. Our problems birth our happiness, along with slightly better, slightly upgraded problems. See: it’s a never-ending upward spiral. And if you think at any point you’re allowed to stop climbing, I’m afraid you’re missing the point.
</p><p> 50. It turns out that merely feeling good about yourself doesn’t really mean anything unless you have a good reason to feel good about yourself.
</p><p> 51. The true measurement of self-worth is not how a person feels about her positive experiences, but rather how she feels about her negative experiences.
</p><p> 52. Our lives today are filled with information from the extremes of the bell curve of human experience, because in the media business that’s what gets eyeballs, and eyeballs bring dollars. That’s the bottom line. Yet the vast majority of life resides in the humdrum middle. The vast majority of life is un extraordinary, indeed quite average.
</p><p> 53. We all have emotional blind spots. Often they have to do with the emotions that we were taught were inappropriate growing up.
</p><p> 54. Values underlie everything we are and do. If what we value is unhelpful, if what we consider success/failure is poorly chosen, then everything based upon those values—the thoughts, the emotions, the day-to-day feelings— will all be out of whack.
</p><p> 55. Values underlie everything we are and do. If what we value is unhelpful, if what we consider success/failure is poorly chosen, then everything based upon those values—the thoughts, the emotions, the day-to-day feelings— will all be out of whack. Everything we think and feel about a situation ultimately comes back to how valuable we perceive it to be.
</p><p> 56. For many people this passes as self-awareness. And yet, if they were able to go deeper and look at their underlying values, they would see that their original analysis was based on avoiding responsibility for their own problem, rather than accurately identifying the problem.
</p><p> 57. People’s perceptions and feelings may change,  but the underlying values, and the metrics by which those values are assessed, stay the same.
</p><p> 58. In fact, in my experience, the more uncomfortable the answer, the more likely it is to be true.
</p><p> 59. Problems may be inevitable, but the meaning of each problem is not. We get to control what our problems mean based on how we choose to think about them, the standard by which we choose to measure them.
</p><p> 60. Our values determine the metrics by which we measure ourselves and everyone else.
</p><p> 61. If you want to change how you see your problems, you have to change what you value and/or how you measure failure/success.
</p><p> 62. Good values are 1) reality-based, 2) socially constructive, and 3) immediate and controllable. Bad values are 1) superstitious, 2) socially destructive, and 3) not immediate or controllable.
</p><p> 63. As a rule, people who are terrified of what others think about them are actually terrified of all the shitty things they think about themselves being reflected back at them.)
</p><p> 64. Often the only difference between a problem being painful or being powerful is a sense that we chose it, and that we are responsible for it.
</p><p> 65. Often the only difference between a problem being painful or being powerful is a sense that we chose it, and that we are responsible for it. If you’re miserable in your current situation, chances are it’s because you feel like some part of it is outside your control—that there’s a problem you have no ability to solve, a problem that was somehow thrust upon you without your choosing.
</p><p> 66. We don’t always control what happens to us. But we always control how we interpret what happens to us, as well as how we respond.
</p><p> 67. A lot of people hesitate to take responsibility for their problems because they believe that to be responsible for your problems is to also be at fault for your problems.
</p><p> 68. There’s a difference between blaming someone else for your situation and that person’s actually being responsible for your situation. Nobody else is ever responsible for your situation but you. Many people may be to blame for your unhappiness, but nobody is ever responsible for your unhappiness but you. This is because you always get to choose how you see things, how you react to things, how you value things. You always get to choose the metric by which to measure your experiences.
</p><p> 69. I am responsible for how i feel. 
</p>
</div>
</>

    )}

